### ISSUE TITLE
Error on running `npm start`

### ISSUE THREAD

**Issue by bitgeeky** [auchenberg/remotedebug-firefox-adapter#6]
On following the instructions mentioned in Readme, it gives errors on doing `npm start`.
OS Version: OS X 10.10.3
Nightly Version: 41.0a1 (2015-05-28)
Firefox Version: 38.0.1
Error with both Firefox and Firefox Nightly:

```
➜  remotedebug-firefox-adapter git:(master) npm start

> remotedebug-firefox-adaptor@0.0.1 start /Users/bitgeeky/projects/remotedebug-firefox-adapter
> node bin/adaptor.js


/Users/bitgeeky/projects/remotedebug-firefox-adapter/node_modules/firefox-client/lib/tab.js:10
module.exports = Tab;
      ^
SyntaxError: Unexpected token .
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/bitgeeky/projects/remotedebug-firefox-adapter/node_modules/firefox-client/lib/browser.js:4:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.30
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! remotedebug-firefox-adaptor@0.0.1 start: `node bin/adaptor.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the remotedebug-firefox-adaptor@0.0.1 start script 'node bin/adaptor.js'.
npm ERR! This is most likely a problem with the remotedebug-firefox-adaptor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/adaptor.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls remotedebug-firefox-adaptor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bitgeeky/projects/remotedebug-firefox-adapter/npm-debug.log
```

npm-debug logs:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.5.1
3 info using node@v0.10.30
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart remotedebug-firefox-adaptor@0.0.1
6 info start remotedebug-firefox-adaptor@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info remotedebug-firefox-adaptor@0.0.1 Failed to exec start script
9 verbose stack Error: remotedebug-firefox-adaptor@0.0.1 start: `node bin/adaptor.js`
9 verbose stack Exit status 8
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:98:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:98:17)
9 verbose stack     at maybeClose (child_process.js:756:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
10 verbose pkgid remotedebug-firefox-adaptor@0.0.1
11 verbose cwd /Users/bitgeeky/projects/remotedebug-firefox-adapter
12 error Darwin 14.3.0
13 error argv "node" "/usr/local/bin/npm" "start"
14 error node v0.10.30
15 error npm  v2.5.1
16 error code ELIFECYCLE
17 error remotedebug-firefox-adaptor@0.0.1 start: `node bin/adaptor.js`
17 error Exit status 8
18 error Failed at the remotedebug-firefox-adaptor@0.0.1 start script 'node bin/adaptor.js'.
18 error This is most likely a problem with the remotedebug-firefox-adaptor package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node bin/adaptor.js
18 error You can get their info via:
18 error     npm owner ls remotedebug-firefox-adaptor
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by auchenberg** [comment]
I just pushed an update to https://github.com/auchenberg/firefox-client. Can you try again?

**Comment by bitgeeky** [comment]
Thanks ! Update fixed the error for me. Looks like this is still a work in progress. I am working on similar projects and saw your other projects and initiatives for unifying remote debugging protocols.
Seriously, great work :+1:   Closing the issue.

**Comment by bitgeeky** [comment]
Thanks ! Update fixed the error for me. Looks like this is still a work in progress. I am working on similar projects and saw your other projects and initiatives for unifying remote debugging protocols.
Seriously, great work :+1:   Closing the issue.

**Comment by auchenberg** [comment]
Cool, great to hear! The basics are in place, so if you have time please contribute and help map "the rest", there's still lots to do for Firefox!
